apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-data
  namespace: search
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
