apiVersion: v1
kind: Service
metadata:
  name: search-api
  namespace: search
  labels:
    app.kubernetes.io/name: search-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: search-api
  ports:
    - name: http
      port: 80
      targetPort: http
