apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: search-api-iap-oauth-client-secret
  namespace: search
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secretmanager
    kind: SecretStore
  target:
    name: search-api-iap-oauth-client-secret
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: search-api-iap-oauth-client-secret
