apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meili-master-key
  namespace: search
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secretmanager
    kind: SecretStore
  target:
    name: meili-master-key
    creationPolicy: Owner
  data:
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: meili-master-key
