apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synonym-redis-auth
  namespace: search
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secretmanager
    kind: SecretStore
  target:
    name: synonym-redis-auth
    creationPolicy: Owner
  data:
    - secretKey: REDIS_AUTH
      remoteRef:
        key: mlops-synonym-redis-auth
