#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_FILE="$ROOT_DIR/docs/conventions/Makefile規約.md"

PHASE_DIRS=(
  "1/study-ml-foundations"
  "2/study-ml-app-pipeline"
  "3/study-hybrid-search-local"
  "4/study-hybrid-search-gcp"
  "5/study-hybrid-search-vertex"
  "6/study-hybrid-search-pmle"
  "7/study-hybrid-search-gke"
)

PHASE_LABELS=(
  "P1"
  "P2"
  "P3"
  "P4"
  "P5"
  "P6"
  "P7"
)

canonical_phase="6/study-hybrid-search-pmle"
mapfile -t CANONICAL_TARGETS < <(
  cd "$ROOT_DIR/$canonical_phase"
  make -s print-canonical-targets 2>/dev/null
)

declare -a PHASE_NA_LISTS=()
for phase in "${PHASE_DIRS[@]}"; do
  na_list="$(cd "$ROOT_DIR/$phase" && make -s print-na-targets 2>/dev/null || true)"
  PHASE_NA_LISTS+=("$na_list")
done

is_na_target() {
  local target="$1"
  local na_blob="$2"
  local pat
  while IFS= read -r pat; do
    [[ -z "$pat" ]] && continue
    pat="${pat//%/*}"
    if [[ "$target" == $pat ]]; then
      return 0
    fi
  done <<< "$na_blob"
  return 1
}

{
  echo "# Make Command Matrix"
  echo ""
  echo "Auto-generated by tools/generate_makefile_md.sh."
  echo ""
  echo "## Reading Guide"
  echo ""
  echo '- `Make target` is the user-facing public API.'
  echo '- `scripts/*` is the internal implementation behind those targets.'
  echo "- Keep target names stable; migrate implementation paths underneath them."
  echo "- For naming and migration policy, see [スクリプト規約.md](スクリプト規約.md) (same dir under docs/conventions/)."
  echo ""
  echo "## Canonical Vocabulary"
  echo ""
  for target in "${CANONICAL_TARGETS[@]}"; do
    echo "- $target"
  done
  echo ""
  echo "## Phase Support Matrix"
  echo ""
  echo "| target | ${PHASE_LABELS[0]} | ${PHASE_LABELS[1]} | ${PHASE_LABELS[2]} | ${PHASE_LABELS[3]} | ${PHASE_LABELS[4]} | ${PHASE_LABELS[5]} | ${PHASE_LABELS[6]} |"
  echo "|---|---|---|---|---|---|---|---|"

  for target in "${CANONICAL_TARGETS[@]}"; do
    row="| $target"
    for i in "${!PHASE_DIRS[@]}"; do
      if is_na_target "$target" "${PHASE_NA_LISTS[$i]}"; then
        row+=" | N/A"
      else
        row+=" | OK"
      fi
    done
    row+=" |"
    echo "$row"
  done
} > "$OUT_FILE"

echo "Generated: $OUT_FILE"
