#!/usr/bin/env bash
# Generate docs/conventions/Makefile規約.md from the canonical Makefile.
# Flat-repo version: no per-phase walk, no Phase Support Matrix.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MAKEFILE="$ROOT_DIR/Makefile"
OUT_FILE="$ROOT_DIR/docs/conventions/Makefile規約.md"

if [[ ! -f "$MAKEFILE" ]]; then
  echo "Makefile not found at $MAKEFILE" >&2
  exit 1
fi

{
  echo "# Make Command Matrix"
  echo
  echo "Auto-generated by \`tools/generate_makefile_md.sh\` from the root \`Makefile\`."
  echo "Do not hand-edit; re-run the generator after Make target changes."
  echo
  echo "## Reading Guide"
  echo
  echo "- \`Make target\` is the user-facing public API."
  echo "- \`scripts/*\` is the internal implementation behind those targets."
  echo "- Keep target names stable; migrate implementation paths underneath them."
  echo "- For naming and migration policy, see [スクリプト規約.md](スクリプト規約.md)."
  echo
  echo "## Targets by Section"
  echo

  awk '
    BEGIN { section = "(uncategorized)" }
    /^# ----- .* -----/ {
      line = $0
      sub(/^# ----- /, "", line)
      sub(/ -----.*$/, "", line)
      section = line
      next
    }
    /^[a-zA-Z0-9_-]+:.*##/ {
      target = $0
      sub(/:.*$/, "", target)
      desc = $0
      sub(/^[^#]*##[ \t]*/, "", desc)
      gsub(/\|/, "\\|", desc)
      print section "\t" target "\t" desc
    }
  ' "$MAKEFILE" | awk -F'\t' '
    BEGIN { section = "" }
    {
      if ($1 != section) {
        if (section != "") print ""
        print "### " $1
        print ""
        print "| target | description |"
        print "|---|---|"
        section = $1
      }
      print "| `" $2 "` | " $3 " |"
    }
  '
} > "$OUT_FILE"

echo "Generated: $OUT_FILE"
